### ISSUE TITLE
New command fails on MacOS

### ISSUE THREAD

**Issue by chills42** [codesections/mnemonic#2]
After running `cargo install mn` I am unable to create a new entry using the tool.

```
=> mn -n note                                              
The file /Users/username/Library/Application Support/mn/note.md does not exist.
```
I checked, and the mn directory was missing, so I created it and tried again, with the same issue.

```
=> mkdir /Users/username/Library/Application\ Support/mn
=> mn -n note                                             
The file /Users/username/Library/Application Support/mn/note.md does not exist.
```

Just to confirm, I also created the file, then tried again, with a reasonable response.

```
=> touch /Users/username/Library/Application\ Support/mn/note.md
=> mn -n note                                                     
note already exists.  Did you mean to edit it instead?
```

**Comment by codesections** [comment]
That is a serious bug—thanks for pointing it out!  Does `mn --add` also exhibit the same buggy behavior or does that command work?

**Comment by chills42** [comment]
Looks like add works (I tried `mn --add hello` and ended up with a new entry).

**Comment by sinistersnare** [comment]
Yeah, `--new` does not work for me, but `--add` does work.

**Comment by codesections** [comment]
Just pushed a v0.1.7 that should resolve this issue; please let me know if it does and I'll close this.

(In case you're curious: I believe the issue was with how your default editor behaves when asked to open a file that does not yet exist.  I had tested with vim, and when asked to open a file that doesn't exist, it creates that file—but apparently other editors do not do so and instead exit with an error.  I've fixed `mn` to always create the file before attempting to open it, which should work regardless of the editor (or if no editor is set and `mn` falls back on opening with `open` or `xdg-open`.)

Thanks again for pointing this out!

**Comment by chills42** [comment]
Awesome! I'd have hit this because I have no editor set then. Thanks for the fix (now off to set my editor so that I get vim instead of a fallback).

**Comment by codesections** [comment]
Closed as fixed
